### ISSUE TITLE
Create new groups

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#1]
* "NEII Conformant Data Services" ("Group 1")
* "NEII - Experimental Data Services" ("Group 2")
* "Context Layers" ("Group 3")

**Comment by azzerger** [comment]
Could we make it as follows (minor grammatical change)

NEII Data Services - Conformant ("Group 1")
NEII Data Services - Experimental ("Group 2")
Contextual Layers ("Group 3")

**Comment by azzerger** [comment]
Under NEII Data Services - Conformant we would also like the following sub-groupings to cluster our services (I have included how current data could be mapped in brackets):
Air (solar)
Biota 
Land
Oceans (eReefs, reeftemp once on-boarded)
Water (geofabric)
Other

Noting that we may not have data for some categories so we should not include them until we have a data service present from a user experience perspective

**Comment by stevage** [comment]
<img width="708" alt="screenshot 2016-04-04 16 57 46" src="https://cloud.githubusercontent.com/assets/678344/14240214/6d25deee-fa86-11e5-895d-b5ca5a91a341.png">

Note that only Air, Oceans and Water are visible by default. (The others only show up due to the URL).

**Comment by azzerger** [comment]
Steve, should this be visible at http://nationalmap.research.nicta.com.au/neii/? 

Changes look good in the screen grab but it would be nice to see them in the dev site.

Andre

**Comment by azzerger** [comment]
Cancel that - it now works in the dev site - I probably needed to wait a little longer. 

Andre
