### ISSUE TITLE
Change URL to neii.gov.au/viewer

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#10]
This requires cooperation between NEII's web team and our hosting.

**Comment by ChantelleDoan** [comment]
I have a contact in our Digital Data team - Adam Hough who is looking into this from our end and will liase with you to plan/co-orindate this change.

**Comment by stevage** [comment]
He should get in touch with peter.hassall@nicta.com.au directly, but please CC me.

**Comment by stevage** [comment]
Ok, this is basically solved. The only hurdle is we need to change the proxy URL to `proxy/` when deploying to prod.

**Comment by ChantelleDoan** [comment]
Thanks Steve.  I see it is working on production now.

Also, on the howto.html page (http://neii.gov.au/viewer/help/howto.html#GetStartedWithTheNationalMap), could you help updates the 2 links referencing to http://neiiviewer.nicta.com.au<http://neiiviewer.nicta.com.au/>


1.     " Launch the NEII Viewer<http://neiiviewer.nicta.com.au/>" tab on the page header

2.      First dot point on this page "Display the NEII Viewer by using the URL http://neiiviewer.nicta.com.au<http://neiiviewer.nicta.com.au/>.
[cid:image002.png@01D18F22.96CD9310]

Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by stevage** [comment]
Ok, I've done that - but it won't be visible at neii.gov.au/viewer until the next production deployment.

Where do you want the help pages to live in the longer term? Within Terria, or in your CMS?

**Comment by ChantelleDoan** [comment]
Thanks Steve.

You are a step ahead of us, we have an action item for us to review where the help pages reside in the longer term.  Will keep you updated.

Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by stevage** [comment]
Marking this as done now. It's accessible at the requested URL, and will work fully on the next production deployment, which I've requested.

**Comment by stevage** [comment]
Ok, this is interesting. We've updated http://neiiviewer.nicta.com.au/ to the latest version (with new skin). However http://neii.gov.au/viewer/ is still showing the old version, which I don't really understand. Is there a caching proxy somewhere? @ChantelleDoan

**Comment by peterhassall** [comment]
It's likely the nginx server doing they proxying needs to re-resolve the IPs of the target. Restarting nginx should resolve the issue.

**Comment by stevage** [comment]
Looks like this is properly resolved now.
