### ISSUE TITLE
Viewer freezes when uploading large json file (approx 95MB)

### ISSUE THREAD

**Issue by mardmaree** [TerriaJS/neii-viewer#100]
I'm not able to upload the JSON file here, but attach the xls file which we convert into JSON before uploading to the Viewer. I can email the JSON file separately.
Please note no error is being produced but when I try to drag/drop the JSON file onto the Viewer it freezes and doesn't allow me to proceed. Please advise what is the current limitation size of file that can be uploaded to the Viewer? This file contains approx 84000 site records. 
Mardi (03) 9616 8347.

**Comment by AnaBelgun** [comment]
@mardmaree Hi. Would you please send us the file by email (if possible) to check? 
ana.belgun@data61.csiro.au

**Comment by AnaBelgun** [comment]
@meh9 tested the file and it has too many points. User advised to split it or host it as a webservice like WMS or ArcGIS MapServer.
