### ISSUE TITLE
Enable BoM team to make changes to config files 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#101]
The Bureau's team would like to be able to make changes to config files for all sections of the catalogue; currently is only possible for 2 sections (not sure which ones)

**Comment by AnaBelgun** [comment]
Issue:  
Currently when new layers are added to the viewer, I update the config files on GitHub with the new layers but due to changes to the Data61 production release cycle, I am not able to push these changes to production.  I made over 12 months ago still on GitHub waiting for production deployment.

User story: 
To allow (BoM staff) users access to the  configs files only (separate from the rest of the source codes) and be able to pushout these files to production.

Branches in GitHub:
- Master
- Neii-newui
- Oldui
- Production

Environments:
Could you help map which of the above branches maps to these below environments?  Thanks. 

- Production:  http://neii.gov.au/viewer/
- Staging: http://neiiviewer.nicta.com.au/
- Staging: http://staging.neiiviewer.nicta.com.au/

**Comment by AnaBelgun** [comment]
@meh9 decided to use GitHub

**Comment by AnaBelgun** [comment]
Customer agreed on 9 July 18.

**Comment by meh9** [comment]
Done, but not as a separate repo - it's part of the main neii-viewer repo.
