### ISSUE TITLE
Add NEMSR data service

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#11]
This is a dataset of environmental monitoring sites, as WFS. It won't be ready for a few months. It will go in "Conformant" data services.

**Comment by stevage** [comment]
I'll create a stub init file, which the NEMSR people can modify and test how their WFS service displays.

**Comment by stevage** [comment]
You can use this as a starting point:

```
{
    "catalog": [
        {
            "name": "NEII Data Services – Experimental",
            "type": "group",
            "isOpen": true,
            "items": [
                {
                    "type": "wfs",
                    "name": "NEMSR sites",
                    "url": "",
                    "layers": ""
                }
            ]
        }
    ]
}
```

**Comment by ChantelleDoan** [comment]
Hi Steve,
Under the master branch, I committed updates to neii-nemsr.json on 16/6.  I was able to see the changes on the staging Viewer on that day but for some reason now, staging viewer is not reflecting thia change.  Could you look into this for me.  Thanks, Chantelle

**Comment by ChantelleDoan** [comment]
Hi Steve,

I will have a final version of the NEMSR config file by tomorrow ready (I will send tomorrow) for the NEMSR production release scheduled for 30 June.
I would like to booked some of your time if possible on 30/6 to assist to deploy it to Viewer Staging and Viewer Production.  

Thanks, Chantelle

**Comment by stevage** [comment]
Just commenting that this is included in the [newui](https://github.com/TerriaJS/neii-viewer/issues/35)

**Comment by ChantelleDoan** [comment]
Hi Steve,
I will close this item as it has been superseded by 
https://github.com/TerriaJS/neii-viewer/compare/master...marissabyrnes:patch-1

Thanks,
Chantelle
