### ISSUE TITLE
Feature info templates

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#12]
We should implement `featureInfoTemplate`s for all current and future services, getting NEII to review them.

**Comment by azzerger** [comment]
Not quite sure what this means but will trust your judgment we need one :)

**Comment by stevage** [comment]
Here's a layer on another one of our maps, without a feature info template. Every attribute from the WMS server is displayed.

![raw](https://cloud.githubusercontent.com/assets/678344/14165966/992ef6f8-f75a-11e5-95cd-326736eec9ec.png)

Here's the same layer with a feature info template. I chose the attributes that I thought were most relevant, and made one of them link somewhere.

![featureinfotemplate](https://cloud.githubusercontent.com/assets/678344/14165967/99314c3c-f75a-11e5-9ab1-050a3b31d70e.png)

Does that make sense?

**Comment by stevage** [comment]
@azzerger Ok, I'm adding feature info templates to the water quality layers. I can't work out what the units should be for the Chlorophyll layers:

<img width="306" alt="screenshot 2016-04-06 15 10 45" src="https://cloud.githubusercontent.com/assets/678344/14306377/df453270-fc09-11e5-82cf-295ac142ae88.png">

I'm guessing it's µg/L but I'm not certain. (My guess is because the high levels would then be around 1 µg/L which is just below the defined "[trigger level](http://www.environment.gov.au/system/files/resources/53cda9ea-7ec2-49d4-af29-d1dde09e96ef/files/nwqms-guidelines-4-vol1.pdf)" of 1.5). Are you able to confirm?

**Comment by stevage** [comment]
Looks like the THREDDS server [can actually report units](http://ereeftds.bom.gov.au/ereefs/tds/ncss/grid/ereefs/mwq_gridAgg_P1A/dataset.xml).

In this case though, it says something pretty unintuitive!

```
<attribute name="unit_id" value="http://environment.data.gov.au/water/quality/def/unit/MicroGramsPerLitre"/>
<attribute name="units" value="mg m-3"/>
```

µg/L are the same as mg/m3, so looks like I was right. I can use the same process to figure out the others (which seem to be "reciprocal metres")
