### ISSUE TITLE
NEII - Add Satellite Imagery layers 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#121]
Add all satellite imagery layers from terria cube https://terria-cube.terria.io/#share=s-mjrTEOhFZ7uInx4GNyOs3bRhHT2 under DEA Production (apart from ITEM, NIDEM, HLTC) and GSKY Blended service: https://terria-cube.terria.io/#share=s-8AxtNDHjGF9TjuM2lkd3kJc5zOe

**Comment by rowanwins** [comment]
Resolved by #124
