### ISSUE TITLE
eReefs title change

### ISSUE THREAD

**Issue by azzerger** [TerriaJS/neii-viewer#14]
Could we change the title of this layer to be as follows:

"eReefs Marine Water Quality"

To appear how it does in the NEII Catalogue

**Comment by azzerger** [comment]
Steve, should this now be visible at http://neiiviewer.nicta.com.au/ given you have closed this? Or perhaps there is a delay before its visible in production? Andre

**Comment by stevage** [comment]
Sorry, I meant to say. "Closed" in this context means the code is in the master branch, and will be included in the next public update, whenever that happens (nothing scheduled atm). We don't currently have a public development instance running, but we should probably set one up.

**Comment by stevage** [comment]
Actually, we do have a development instance: http://nationalmap.research.nicta.com.au/neii/

I'll look at setting it up to automatically display the changes.

**Comment by azzerger** [comment]
That sounds great – I had a quick look and that works well as a dev instance.
