### ISSUE TITLE
NEII - June 2020 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#147]
- [ ] fix the parameter https://github.com/TerriaJS/neii-viewer/issues/143

- [ ] update to latest TerriaJS version

- [ ] https://github.com/TerriaJS/neii-viewer/issues/148#issuecomment-624382286

**Comment by nf-s** [comment]
Related https://github.com/TerriaJS/terriajs/issues/4218

**Comment by AnaBelgun** [comment]
Ana to discuss  with the Bureau to replace this June release with MobX release first 2 weeks of Sep

**Comment by AnaBelgun** [comment]
email sent to Martin 
will close this ticket; superseeded by MobX release in Sept 2020
