### ISSUE TITLE
Catalog Conversion Notes

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/neii-viewer#157]
#### Models required
- wfs-getCapabilities
- wfs
- wms-getCapabilities
- esri-mapServer

#### Properties missing for converter
- colorScaleMinimum
- colorScaleMaximum
- ignoreUnknownTileErrors
- featureInfoTemplate.formats

####  Properties missing in mobx?
- abstract
- preserveOrder
- ~custodian~ should be dataCustodian, this is an error in the NEII catalog

**Comment by soyarsauce** [comment]
@KeyboardSounds still working on it, https://github.com/TerriaJS/catalog-converter/issues/12 can prove useful

**Comment by KeyboardSounds** [comment]
Missing:
- featureInfoTemplate.formats
- wms-getCapabilities
- wfs-getCapabilities

**Comment by nf-s** [comment]
WMS group catalog converter issue - https://github.com/TerriaJS/catalog-converter/issues/10

**Comment by nf-s** [comment]
esri-mapServer support is in PR - https://github.com/TerriaJS/catalog-converter/pull/17

**Comment by AnaBelgun** [comment]
replaced with issues for specific datasets
