### ISSUE TITLE
Themes - add services count

### ISSUE THREAD

**Issue by azzerger** [TerriaJS/neii-viewer#16]
Steve

Given we have moved to thematic groupings (Air, Land, Oceans, Water, Biota) could we include an indication best each group as to the number of datasets in the group. For example at present it would look like:

We would need to change the count each time we add new data but I guess that's trivial.

Oceans (2)
Water (1)
Air (1)

Andre

**Comment by stevage** [comment]
![screenshot 2016-04-05 09 53 43](https://cloud.githubusercontent.com/assets/678344/14267507/4f02c34e-fb14-11e5-94a9-12270b0b9406.png)

Looks quite good IMHO.

**Comment by azzerger** [comment]
Indeed – which raises a question – should we include the other groups and just suffix with (0)?

Andre

**Comment by stevage** [comment]
From the perspective of communicating to users what data is available and what is planned, I quite like that actually:

![screenshot 2016-04-05 10 07 58](https://cloud.githubusercontent.com/assets/678344/14267715/67af1c10-fb16-11e5-87b3-9056b031f194.png)

I'll leave that in for now, and you can change your mind later if needed.
