### ISSUE TITLE
GetCapabilities failing for NM_Hydrology_and_Marine_Points

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/neii-viewer#169]
GetCapabilities is returning 400 bad request for http://gaservices.ga.gov.au/site_7/services/NM_Hydrology_and_Marine_Points/MapServer/WMSServer?request=GetCapabilities&service=WMS&version=1.3.0

**Comment by AnaBelgun** [comment]
This url needs updating with: 
http://services.ga.gov.au/gis/rest/services/NM_Hydrology_and_Marine_Points/MapServer

**Comment by nf-s** [comment]
These layers are now working, do I still need to swap the URL?

The new URL does not support WMS, so I will need to change the layers to ArcGisMapServerCatalogItems

**Comment by AnaBelgun** [comment]
@nf-s if the ArcGis ones work, yes

**Comment by nf-s** [comment]
Done!
