### ISSUE TITLE
Water > Geofabric > Surface Hydrology datasets have many issues

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/neii-viewer#170]
For every layer in this group:
1) unknown tile error seems to break entire layer
2) information is missing from the catalog item description - left is v7, right is v8
![image](https://user-images.githubusercontent.com/3796838/100710582-0a2a7400-3404-11eb-8ed8-53f75f71836d.png)
3) bounding boxes are wrong: 
    > "The rectangle in dev excludes WA, most of Tasmania, and also the far east coast around the Qld/NSW border area.  These areas all have data and the outline box should not have changed from the existing one.
Others have the same issue."

**Comment by nf-s** [comment]
Layers are now working, there is a slight difference in how metadata is displayed.

For example - `Service Description`

![image](https://user-images.githubusercontent.com/6187649/115347590-ee7a0b80-a1f4-11eb-9fe2-718788c97550.png)

**Comment by AnaBelgun** [comment]
@nf-s this should be ok for now (with the slight difference)

**Comment by nf-s** [comment]
Hi @AnaBelgun what needs to be done for this?
http://beta.neiiviewer.nicta.com.au/#share=s-rauT650IRTm8bdbt9fe4eHxrEEC

The differences between "Service Description" from v7 -> v8 is something which is applied to all WMS layers.

If they don't want the big table thing - this PR might be a good solution https://github.com/TerriaJS/terriajs/pull/5139

**Comment by nf-s** [comment]
https://github.com/TerriaJS/terriajs/pull/5139 has been closed
