### ISSUE TITLE
Global Horizontal Exposure layers not loading

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/neii-viewer#172]
In v8, an error box appears and the layer doesn't load, citing a 400 error.
In v7, the 400 error appears in the network tab, but the layer doesn't break and loads correctly.

url: http://neii.bom.gov.au/services/solarclim/wms/data/annClim_gloHorExp1Day.nc?service=WMS&version=1.1.1&sld_version=1.1.0&request=DescribeLayer&layers=mean_exposure

**Comment by nf-s** [comment]
These are now working
