### ISSUE TITLE
NEII - Landing page pop up with survey

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#187]
Update 27 Aug 2021 following discussion with BoM's NEII team: 
- create a pop up appearing on NEII v7: http://neii.gov.au/viewer/ 
- use the NationalMap v7 pop up template (because it has the preview beta button built in)
![image](https://user-images.githubusercontent.com/18452161/131074373-4bfa03cd-5d85-4e2e-87bc-9dbb31858fa6.png)
- include the same button to direct users to the Beta version of NEII https://beta.neiiviewer.nicta.com.au/
- include wording ("Welcome to the NEII Data Map Viewer. Please complete our short survey about the current use of NEII Viewer") and link to NEII short user survey https://neii.gov.au/neii-customer-survey

**Comment by AnaBelgun** [comment]
https://neii-viewer.dev.saas.terria.io/

**Comment by wibily** [comment]
discussion around whether to put it on current prod: http://neii.gov.au/viewer/ or https://beta.neiiviewer.nicta.com.au/

**Comment by wibily** [comment]
Ana: decision to plonk it on http://neii.gov.au/viewer/

**Comment by wibily** [comment]
should use whatever is in v7 whatever that may be

**Comment by philipgrimmett** [comment]
**Concept sketch: desktop/tablet and mobile layouts**
![Screen Shot 2021-08-31 at 1 16 22 pm](https://user-images.githubusercontent.com/5292858/131457474-97660c5d-8210-4fd1-a7a1-e93f17ef1947.png)

**Concept sketch: dismissible banner to announce beta maps**
![NEII banner](https://user-images.githubusercontent.com/5292858/131458596-13ff16a4-1dbb-42eb-aaa7-16de240dab80.png)

**Desktop/tablet/mobile behaviour**
Animate in survey panel (slide up from bottom) ~2 seconds after all other modals/tooltips have been dismissed (e.g. disclaimer, welcome, help, story prompt)

**Comment by AnaBelgun** [comment]
@martin-bom hi, would you please have a look at the design above and let us know if we can go ahead? 
Our UX team has advised against having 2 links, requiring 2 actions from the users in the same modal (i.e. a link to the Beta version and another link to the survey). It will confuse the users and not give you the required result (i.e. finding more information from users on how they actually use NEII). 
Hence the design has only one link, to the survey.

**Comment by martin-bom** [comment]
Hi @AnaBelgun Ana, 

Thanks for the information. So that means the link to beta version will not be presented during the survey period. Understood.

Regards,
Martin

**Comment by AnaBelgun** [comment]
yes, we're trying to see if we can have a discrete banner at the top but if it takes too long, we might not wait anymore and go ahead just with the survey

**Comment by martin-bom** [comment]
Thank you Ana, I will come back to you asap. In my opinion I like the popup at the bottom right hand corner. Nice and clear.

**Comment by martin-bom** [comment]
Hi @AnaBelgun Ana, I got some feedbacks from my team on the popup.

Can the message in the popup be:
"Welcome to the NEII Data Map Viewer. Please complete our short survey about <b>your</b> use of <b>the NEII website</b>"

Besides, can the popup sit at the middle of the screen?

Thank you.

**Comment by AnaBelgun** [comment]
hi @martin-bom ok, will do that and send you the UAT for release to check.

**Comment by philipgrimmett** [comment]
Updated survey prompt prototype: https://invis.io/HS11NPNRVF2P#/457900174_NEII_Map

**Comment by martin-bom** [comment]
Hi @philipgrimmett, the updated wordings in the survey prompt is great, thank you.

**Comment by AnaBelgun** [comment]
done
