### ISSUE TITLE
NEII - Add North Australia Automated Marine weather and oceanographic stations (AIMS) 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#189]
- [ ] add the following service under the Conformant - Air group 
https://geoserver.data.aims.gov.au/ows?service=WFS&version=1.0.0&request=GetCapabilities
![image](https://user-images.githubusercontent.com/18452161/131075288-e30807b0-ccf9-490f-9e4f-b402f20cb672.png)

Hi @martin-bom 
How shall we name the new subgroup? current name of service is not very helpful for users.

**Comment by martin-bom** [comment]
@AnaBelgun Hi Ana we would like to keep the name as same as in Version 7. Thank you.

**Comment by nf-s** [comment]
The link https://geoserver.data.aims.gov.au/ows?service=WFS&version=1.0.0&request=GetCapabilities is currently returning "Server not found":

![image](https://user-images.githubusercontent.com/6187649/149923191-060f9a48-d857-48b8-a318-7f0df2879477.png)

**Comment by AnaBelgun** [comment]
@martin-bom we should not re-add this unless it's working. I'll close this ticket until further notice.
