### ISSUE TITLE
CRS Support?

### ISSUE THREAD

**Issue by domlowe** [TerriaJS/neii-viewer#19]
Hi,

I'm working with @azzerger on the NEII NEMSR project at the moment.
This is more of a question than an issue:

Are you able to outline what, if any, support the viewer has for projecting data in different coordinate reference systems (e.g. GDA94, WGS84 etc. etc.)?

Also, what, if any, support there is for the use of coordinate reference systems in GeoJSON uploaded to the viewer?

Thanks,

Dom

**Comment by stevage** [comment]
Interesting question. From memory, the 3D mode (Cesium) supports different projections, but the 2D mode (Leaflet) is more limited - definitely the case for WMS layers, at least. I think support in GeoJSON may be better but I'll have to do some testing to confirm this. GeoJSON itself certainly [supports different CRS](http://geojson.org/geojson-spec.html#coordinate-reference-system-objects).

Can you tell me a little bit more about what kinds of layers and CRS you need to be supported?

**Comment by domlowe** [comment]
There's no specific requirements at this stage - right now I'm just trying to understand the status quo to see if there are any implications for NEMSR.

We potentially have data in few different CRSs e.g. some in GDA94, some in WGS84 (in practice these are very close but not identical), possibly others, and I'm trying to understand to what extent re-projection (in general)  is supported by the viewer and also what coordinate reference system the viewer 'expects' the lat lons to be in.

Upon further inspection - looking at the WMS requests I can see the viewer requests data as EPSG:3857 which is Web Mercator (as used in Google Maps etc) and uses metres (eastings/northings) so I suspect that any GeoJSON file which uses lat, lon is probably being converted on the fly to Web Mercator based on some assumption that the lat lons provided are probably WGS84 (aka EPSG:4326). 

As you point out the current GeoJSON spec supports a 'crs' object so I suppose the question is then whether the viewer is capable of inspecting the 'crs' property of GeoJSON and applying it when converting input lat lons from any different source CRS (e.g. GDA94) into EPSG:3857.

I will try and and test this out too when I get a chance.

**Comment by domlowe** [comment]
Note that the current draft of the next version of GeoJSON essentially removes CRS support:
https://datatracker.ietf.org/doc/draft-ietf-geojson/

So maybe it's a moot point...

**Comment by rowanwins** [comment]
GeoJSON will be reprojected using [terriajs-server](https://github.com/TerriaJS/terriajs-server) if it contains a `crs` property in the FeatureCollection.

**Comment by stevage** [comment]
Also, yeah, CRS are very much deprecated in current GeoJSON files.
