### ISSUE TITLE
NEII - Data missing frequency level dropdown

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#191]
To test: 
- In v7, the Storage Level data had 6 frequency levels to select: http://neii.gov.au/viewer/#share=s-vsJ2KYFqOrvvI5CiFUoE6OPk3ZR
 
![image](https://user-images.githubusercontent.com/18452161/131077341-e27a5146-c7ec-4250-a9b1-0af17cd372b1.png)

- in v8, same data had lost the drop down completely https://beta.neiiviewer.nicta.com.au/#share=s-ht27SbZh4gwCDgTbICpUN4oMwy7

![image](https://user-images.githubusercontent.com/18452161/131077415-a916ebaa-ceea-48e3-8882-bbc9712a785d.png)

**Comment by wibily** [comment]
once there is an understanding of the problem, talk with Ana as SOS will probably be a rabbit hole

**Comment by wibily** [comment]
problem appears to be from a v7-v8

**Comment by na9da** [comment]
Fix: https://github.com/TerriaJS/terriajs/pull/6059
