### ISSUE TITLE
NEII - ideal zoom missing for some data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#192]
The ideal zoom is missing for some data in v8. 

To test: 

- in v7, http://neii.gov.au/viewer/#share=s-vsJ2KYFqOrvvI5CiFUoE6OPk3ZR
- in v8, https://beta.neiiviewer.nicta.com.au/#share=s-zWGNO2cUVoyFD5Y85UvCr2WZZCU 

![image](https://user-images.githubusercontent.com/18452161/131077689-0f6483ca-078f-4541-86d4-74fa756cfe3b.png)

**Comment by nf-s** [comment]
Fixed in dex
