### ISSUE TITLE
NEII - Re add Related Maps button 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#193]
Re-add related maps to the top menu

Use NSW Digital Twin Related Maps list 

![image](https://user-images.githubusercontent.com/18452161/131077853-66c697c5-e20b-470e-b181-448ceba131eb.png)

**Comment by nf-s** [comment]
Currently we cannot add Related maps to SaaS maps https://github.com/TerriaJS/terriajs/issues/3847

**Comment by AnaBelgun** [comment]
Unfortunately we will have to park this one.
