### ISSUE TITLE
Add Water Data Online using SOS

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#2]
Add water from http://www.bom.gov.au/waterdata/

This will require developing SOS integration in TerriaJS.

**Comment by stevage** [comment]
Is this API available yet? What is the endpoint? Any documentation?

**Comment by stevage** [comment]
Ping @azzerger

**Comment by domlowe** [comment]
fyi The WDO SOS endpoint is here:
http://www.bom.gov.au/waterdata/services

See the last question on the FAQ tab here for documentation:
http://www.bom.gov.au/waterdata/

It supports GET and SOAP bindings (not POST).

**Comment by stevage** [comment]
Great, thanks.

http://www.opengeospatial.org/standards/sos

http://www.bom.gov.au/waterdata/services?service=SOS&version=2.0&request=GetCapabilities

**Comment by ChantelleDoan** [comment]
Chantelle co-ordinate testing with the WDO team.

**Comment by ChantelleDoan** [comment]
Testing feedback from Jo:
After a quick initial look at this, I must say I am impressed. I really like the use of colour scale and dot size to represent value – e.g. the very large dot for Lake Argyle. I like the feature to measure distance between two points (or stations).
Does the player adjust the station dots according to value/availability of data? 
One thing I think is needed, and something we might need to give you, is information about the time series made available. E.g. that it is sourced from external data providers, Storage Volume is as supplied (not accessible volume…), maybe rules as to how averages are generated. We have this kind of info on the WDO About & FAQ as you will recall.

Regards
Jo
