### ISSUE TITLE
Splash screen for http://nationalmap.research.nicta.com.au/neii/

### ISSUE THREAD

**Issue by azzerger** [TerriaJS/neii-viewer#20]
Steve

As the staging/research site is visible publically I think a simple splash screen a bit like the AREMI splash screen is warranted and that points to neii.gov.au/viewer - the following text would probably do the trick:

NEII Viewer Experimental Staging Site

You have arrived at the NEII Viewer (neii.gov.au/viewer) experimental staging site. Users seeking robust operational data should go direct to neii.gov.au/viewer. This site is used for user acceptance testing including experimental work with supporting web data services. 

Continue Button, Visit operational NEII Viewer button

**Comment by stevage** [comment]
Good idea, I've done that before for the Northern Australia map.

**Comment by stevage** [comment]
Had a bit of trouble upgrading the dev site in order to be able to handle this, but it's done now.

**Comment by azzerger** [comment]
Steve

That solution works really well – makes it very clear. Regards

Andre
