### ISSUE TITLE
NEII - v8 release

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#203]
- [x] https://github.com/TerriaJS/neii-viewer/issues/189
- [x] https://github.com/TerriaJS/neii-viewer/issues/191
- [x] https://github.com/TerriaJS/neii-viewer/issues/192
- [ ] https://github.com/TerriaJS/neii-viewer/issues/193
- [x] https://github.com/TerriaJS/neii-viewer/issues/194
- [x] https://github.com/TerriaJS/neii-viewer/issues/195
- [x] https://github.com/TerriaJS/neii-viewer/issues/204
- [x] https://github.com/TerriaJS/neii-viewer/issues/215

**Comment by nf-s** [comment]
All done except for Related Maps feature
