### ISSUE TITLE
Digital Earth Australia endpoint configuration is not working

### ISSUE THREAD

**Issue by martin-bom** [TerriaJS/neii-viewer#204]
![image](https://user-images.githubusercontent.com/58055147/135808659-d27addb3-20c6-4990-a513-e1f19a9debd5.png)

Is it because they now only support WMS version 1.3.0? Thank you.

**Comment by martin-bom** [comment]
All the endpoints fixed in #127 no longer working again. Thank you.

**Comment by AnaBelgun** [comment]
hi @martin-bom the same end point seems to work on v8: https://neii-viewer.dev.saas.terria.io/#share=s-lFct8pgO0VtvcKfyy4uHCUYqbZD
this might be another reason we should migrate as soon as possible.

**Comment by nf-s** [comment]
I'm going to close this issue as it is working in v8, it will be fixed when we migrate
