### ISSUE TITLE
NEII - SOS water course discharge / levels stop at 2020

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#205]
SOS water course discharge levels stop showing data at 2020 or earlier. No points showing data beyond 2020. 

https://nationalmap.gov.au/#share=s-ehvpoEH0ULAd3wEgKW7Ehm3SQxT

![image](https://user-images.githubusercontent.com/18452161/138207305-8738c569-0917-46e9-8d49-e9000514614d.png)

![image](https://user-images.githubusercontent.com/18452161/138207352-968496b9-3896-44ad-ad60-5613eabdd910.png)

Same for watercourse levels: 
https://nationalmap.gov.au/#share=s-zO49H0kB25jBBOjAuT4H3D1IMav
![image](https://user-images.githubusercontent.com/18452161/138207451-a28106a4-90fb-4b14-a862-0535ca2a0441.png)

**Comment by martin-bom** [comment]
@AnaBelgun Just checked the URL again https://nationalmap.gov.au/#share=s-zO49H0kB25jBBOjAuT4H3D1IMav and it's now showing 2021 data.

**Comment by AnaBelgun** [comment]
For the yearly ones, it makes sense to have latest data in Jan 2021. I'd like to re-check it for daily/monthly when the new release is done this week and the dropdown frequency is merged.
