### ISSUE TITLE
New v8 testing: styling issue

### ISSUE THREAD

**Issue by martin-bom** [TerriaJS/neii-viewer#217]
Hover over text color change in catalogue listing (can we configure by ourselves?):
    Current version:
![image](https://user-images.githubusercontent.com/58055147/138634712-704da8b8-0264-4ccf-bb59-5a70ac532d0a.png)

    New version:
![image](https://user-images.githubusercontent.com/58055147/138634762-53fa386f-e06b-418a-b3b9-78d2295984f5.png)

**Comment by nf-s** [comment]
Fixed in dev
