### ISSUE TITLE
New v8 testing: some service layers cannot be displayed/error

### ISSUE THREAD

**Issue by martin-bom** [TerriaJS/neii-viewer#218]
After fixing, to be moved to NationalMap. 

1) Biota --> NSW BioNet Flora survey data collection.

New version:
![image](https://user-images.githubusercontent.com/58055147/138638335-b8f24354-467e-42ac-89c9-adc0bb351062.png)

Current version:
![image](https://user-images.githubusercontent.com/58055147/138638368-ccb3dd1e-cda7-42c7-89be-5957fb6bb2e7.png)

2) Air --> All layers under "Australia Climate (BoM)"
Error returned:
![image](https://user-images.githubusercontent.com/58055147/138641076-8e43b5cf-4fd6-477f-8da4-ad6e6056c5e2.png)

**Comment by martin-bom** [comment]
Hi @AnaBelgun this high priority issue seems not yet fixed. Will it be fixed in the upcoming v8 upgrade? Thank you.

**Comment by AnaBelgun** [comment]
hi @martin-bom you're right; this has been missed in the list of fixes.
If these datasets will be transferred to NationalMap, we should fix them before doing that. 
another thought, maybe instead of working on the migration now to v8, maybe we use that development time for transfer to nationalmap and decommissioning message etc. It is a better use of resources.

**Comment by martin-bom** [comment]
Hi @AnaBelgun 
Do you mean instead of pushing the neii-viewer to v8, the resources will be shifted to merging datasets to nationalmap and fix this issue? Is that correct?
Regards Martin

**Comment by AnaBelgun** [comment]
hi @martin-bom yes, that's correct. And we can start now transferring / copying into NationalMap so it's done by end of June. 
This is a time consuming process and will take us at least few months because NationalMap is released every 2nd month with only 2 left this year.

**Comment by martin-bom** [comment]
Hi @AnaBelgun 
I had a meeting with my team this morning about your plan and they were all agreed with that. Thank you Ana!

**Comment by AnaBelgun** [comment]
great. I've started a new ticket just for that: https://github.com/TerriaJS/neii-viewer/issues/223

Let's keep adding data to the list (starting from the top of NEII catalogue) and the group in NationalMap to go to.

**Comment by nf-s** [comment]
1. is fixed https://neii-viewer.prod.saas.terria.io/#share=s-2CU5leUJsYAMhSIujj1REowc0Px

**Comment by nf-s** [comment]
2. is fixed in a PR https://github.com/TerriaJS/terriajs/pull/6173

Test link: http://ci.terria.io/wms-default-params/#clean&https://terria-catalogs-public.storage.googleapis.com/neii/air/dev.json&share=s-3lY810MGaL8u7rfowcbgtcP6Kf4

**Comment by nf-s** [comment]
BOM WMS will be fixed next release

**Comment by nf-s** [comment]
Flora survey test link

http://ci.terria.io/main/#clean&https://terria-catalogs-public.storage.googleapis.com/neii/biota/dev.json&share=s-cTGJ8kGz8Y6OYb7wvCMZfoMhlH5
