### ISSUE TITLE
New v8 testing: color scale range in layers can no longer be updated

### ISSUE THREAD

**Issue by martin-bom** [TerriaJS/neii-viewer#219]
Current version:
![image](https://user-images.githubusercontent.com/58055147/138643912-4a2886da-6e25-43c0-a927-3465c926f3df.png)

New version:
![image](https://user-images.githubusercontent.com/58055147/138643954-2ba4c9e8-eb22-4ff7-9ad2-18a1962221a0.png)

**Comment by nf-s** [comment]
Fixed in dev https://github.com/TerriaJS/saas-catalogs-public/pull/85

Test link: https://neii-viewer.dev.saas.terria.io/

I need to fix default min/max values

**Comment by nf-s** [comment]
Now fixed in beta environment https://neii-viewer.prod.saas.terria.io/#share=s-4HSTKfDhOOuyLbzLQd91IyCovDg

<img width="949" alt="image" src="https://user-images.githubusercontent.com/6187649/144772244-795c4d6b-4b25-4dad-b589-3fc75072a0e0.png">
