### ISSUE TITLE
On-board GA WoFS data to Viewer

### ISSUE THREAD

**Issue by azzerger** [TerriaJS/neii-viewer#22]
Steve, could we please include the GA Water Observations from Space Product available at National Map into the NEII Viewer under the Water Theme (at http://eos.ga.gov.au/geoserver/NFRIP-WOfS/wms) - it can appear as per how layers are grouped and rendered in National Map.

We feel its safe to on-board directly to the production site rather than staging given its already visible at National Map. 

As an experiment for the two layers under the Water theme could you include the Custodian name after the layer name as per the following:

GeoFabric (BoM)
Water Observations from Space (GA)

Andre

**Comment by meh9** [comment]
Just a note that GA notified us that the WoFS service has been migrated to the NCI, and that this is the one that everybody should use from now on:

http://geoserver.nci.org.au/geoserver/NFRIP-WOfS/wms

I don't know when the old service will be decommissioned.

**Comment by azzerger** [comment]
Mats

Thanks – please let me check with GA just to confirm as they had approved the earlier endpoint – I will be in touch shortly

Andre

**Comment by azzerger** [comment]
Mats

You are correct – GA confirmed this is the correct service. Please do bring it into NEII Viewer under the Water Theme as described in the earlier request.

Cheers

Andre

**Comment by stevage** [comment]
Now visible at http://nationalmap.research.nicta.com.au/neii/, just awaiting deployment to prod.

**Comment by azzerger** [comment]
Steve

Thanks - almost :) It seems to be returning a ‘Request has failed’ error when turning on any layer (not only WofS) - perhaps just a temporary problem.

Secondly, after each of the layers in the Water theme could we please include the agency name as a crude means of implementing a ‘facet’ for example:

GeoFabric (BoM)
Water Observations from Space (GA)

If that works well we will do it across all layers.

Thanks

Andre
On 5 May 2016, at 1:41 AM, Steve Bennett <notifications@github.com<mailto:notifications@github.com>> wrote:


Now visible at http://nationalmap.research.nicta.com.au/neii/, just awaiting deployment to prod.

**Comment by stevage** [comment]
Ok, looks like a problem to do with how the staging server is set up - the CORS proxy isn't working. NEII Viewer on that site needs a more recent version of TerriaJS. I think it will work fine in prod, but I'll make the other change.

**Comment by azzerger** [comment]
Thanks Steve, perhaps let me know when it's working again. It's helpful for us to always review in Staging and then action to Production

Andre
