### ISSUE TITLE
NEII v7 Release (only) for decommissioning popup 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#224]
Title: NEII decommissioning
Message: 
The National Environmental Information Infrastructure (NEII) service is being decommissioned in June 2022.
Environmental information will continue to be made available through Australian Government services such as [data.gov.au](https://data.gov.au/), [NationalMap](https://nationalmap.gov.au/) and Research Vocabularies Australia.
If you require assistance in locating specific datasets, or have any questions, please email [environment@bom.gov.au](mailto:environment@bom.gov.au).
Thank you for your interest in NEII.

**Comment by martin-bom** [comment]
Hi @AnaBelgun , can we add the hyperlink for [Research Vocabularies Australia](https://vocabs.ardc.edu.au/)?
Thank you.

**Comment by martin-bom** [comment]
Hi @AnaBelgun , the popup is approved to go ahead. Please feel to free to launch it anytime at your convenience. Thank you.

**Comment by AnaBelgun** [comment]
ok @martin-bom I'll schedule for next sprint starting next week.

**Comment by martin-bom** [comment]
Hi @AnaBelgun @na9da , we would like to update the popup on NEII Viewer as follows:

`Title: NEII decommissioning
Message:
The National Environmental Information Infrastructure (NEII) service is being decommissioned on 15 June 2022.
Environmental information will continue to be made available through Australian Government services such as [data.gov.au](https://data.gov.au/), [NationalMap](https://nationalmap.gov.au/) and Research Vocabularies Australia.
For more details on accessing the environmental information, please go to [the NEII data transition information page](http://www.bom.gov.au/environment/transition.shtml).
If you require assistance in locating specific datasets, or have any questions, please email [environment@bom.gov.au](mailto:environment@bom.gov.au).
Thank you for your interest in, and support of, NEII.`

Thank you.

**Comment by AnaBelgun** [comment]
@na9da is it possible to update the v7 NEII with the pop up sometime this week? The decommission will happen on 15th of June, which leaves less than 4 weeks for users to be notified.

**Comment by martin-bom** [comment]
Hi @AnaBelgun @na9da may I ask when will the popup be available? Thank you.

**Comment by AnaBelgun** [comment]
Hi @martin-bom we've started the release process and it seems a bit more complicated because it's on a very old version hence having lots of braking changes. 
We'll continue working on it and hopefully finalise by end of Monday.

**Comment by na9da** [comment]
Decommissioning popup is now live on https://neii.gov.au/viewer/

Sorry about the delay in deploying, I missed the notifications on this thread.

**Comment by AnaBelgun** [comment]
@martin-bom release done
https://neii.gov.au/viewer/

**Comment by martin-bom** [comment]
Thank you very much @na9da @AnaBelgun . Popup verified okay.
