### ISSUE TITLE
Pushout new neii-water.json to production

### ISSUE THREAD

**Issue by ChantelleDoan** [TerriaJS/neii-viewer#23]
Hi,
We have made some updates to the config file that controls Geofabric data - neii-water.json.  Appreciate if you could review and pushout to production.  Required by Monday 23/5.

Thanks,
Chantelle

**Comment by kring** [comment]
@ChantelleDoan where are these changes?  @stevage is on holiday.

**Comment by ChantelleDoan** [comment]
I tried to attached the json file here but received an error advsing that json file type is not accepted.  How can I attach the json file?

**Comment by ChantelleDoan** [comment]
[neii-water.zip](https://github.com/TerriaJS/neii-viewer/files/273661/neii-water.zip)

**Comment by ChantelleDoan** [comment]
I zipped the file and was able to attach.

**Comment by ChantelleDoan** [comment]
Actually this can be pushed to production today if you are able to action this.

**Comment by ChantelleDoan** [comment]
Steve advise:
The config file that controls Geofabric data is here:
https://github.com/TerriaJS/neii-viewer/blob/master/wwwroot/init/neii-water.json

**Comment by kring** [comment]
The best way to give us updates to the catalog file - or any file in NEII Viewer - is to open a GitHub pull request.  But I should be able to work with the zipped JSON file.  I'll try to get it to production today.

**Comment by ChantelleDoan** [comment]
Great.  Thanks @kring!
I did look at the pull request but didn't know what to do.  If you have some quick instruction/guide that would be great and I can try this next time.

**Comment by kring** [comment]
@ChantelleDoan here is the diff of your changes:
https://github.com/TerriaJS/neii-viewer/pull/24/files

Did you mean to remove the Water Observations from Space layers?

**Comment by azzerger** [comment]
Kevin & Chantelle

I may chime in with a question – WoFS is only showing on the dev/staging site (http://nationalmap.research.nicta.com.au/neii/) so that means we are editing that JSON catalogue file not the production catalogue?

Andre

**Comment by kring** [comment]
@azzerger Yeah I guess the addition of WoFS hasn't been deployed to the production site yet.  If @ChantelleDoan started with the production JSON file when creating the edits, that would explain why it is missing.  I'll add it back.  Sound ok?

**Comment by ChantelleDoan** [comment]
Hi Kevin,

On production, it should not display the WOFS layers.  So the changes in the new file I sent are correct minus one line:

Line 4# Undo change.  Should be
"name": "NEII Data Services – Conformant"

and not
"name": "NEII Data Services – Conformant - GSLB",

Appreciate if you could amend this before committing.  Thanks Kevin.
Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by kring** [comment]
Sorry I'm not totally up on the history here... why aren't we including WoFS in production?

**Comment by kring** [comment]
I removed GLSB.

**Comment by ChantelleDoan** [comment]
This was a test only to see how the WOFS would look on staging.  We still have some work to do before we are ready to release the WOFS to the Viewer.  Ideally these well be added to the NEII Catalogue before we release it on the Viewer and work is still progressing to add these to the Catalogue at this stage.

Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by kring** [comment]
Ok, makes things a bit tricky, we'll need a separate branch for staging versus production.   I'll get that rigged up.

**Comment by kring** [comment]
@ChantelleDoan and @azzerger: the changes are now live at: http://staging.neiiviewer.nicta.com.au.

If everything looks good, I'll change http://neiiviewer.nicta.com.au to point to this as well.  Please give it a more-thorough-than-usual look over, because I haven't deployed NEII Viewer before, so there's a chance I've done something wrong.

**Comment by ChantelleDoan** [comment]
Hi Kevin,

I tested and all display as expected.  Please proceed to pushout to production.  Thanks for all your assistance today.

Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by kring** [comment]
Done!
