### ISSUE TITLE
NEII Viewer Staging

### ISSUE THREAD

**Issue by ChantelleDoan** [TerriaJS/neii-viewer#25]
Hi Nick,

We are working on NEMSR and preparation for a Demo scheduled for 25/5 we would like to update the Staging NEII Viewer.  Can we send you the file to apply?  Out tech lead is Martin Schweitzer <m.schweitzer@bom.gov.au> who has all the details for this request.

I had a look at the Pull Request screen but was not able to identify which was used for the Staging.

Thanks,
Chantelle

**Comment by kring** [comment]
Sorry, what server specifically do you mean by "Staging NEII Viewer"?  And what changes do you want there?  Are these the changes you sent through the other day, or something different?

**Comment by ChantelleDoan** [comment]
Hi Kevin,

Would you be able to help add a new json config file for NEMRS with a single layer to do a demo on
http://staging.neiiviewer.nicta.com.au

To be displayed as the second group under left navigation bar under "NEII Data Services - Conformant"

Group Heading name = National Environmental Monitoring Site
Sub group name = Network
layer name = Orangisation
the layer data url is =
http://104.236.81.25/cgi-bin/mapserv?map=/data/mapfiles/nemsr.map&service=wfs&version=1.1.0&request=getFeature&typename=nemsr_sites&BBOX=-50,100,0,170

If you require further information and if it is easier, my contact number is 0400 953 733

Thanks,
Chantelle

**Comment by stevage** [comment]
Hmm, that WFS layer doesn't seem to support JSON or GML as an output format?

http://104.236.81.25/cgi-bin/mapserv?service=WFS&request=GetFeature&typeName=&version=1.1.0&outputFormat=json&srsName=EPSG%3A4326&map=%2Fdata%2Fmapfiles%2Fnemsr.map&typename=nemsr_sites&BBOX=-50%2C100%2C0%2C170

**Comment by azzerger** [comment]
Steve and Chantelle

cc. Martin

Martin did a dry run of a NEMSR demo this afternoon and we noticed that when the NEMSR is empty (i.e. no records) NEII Viewer returns an error but once it contains records it works – for his demonstration Martin used the following URL and I just repeated the demo with a simple Add Data request against the following URL:

http://104.236.81.25/cgi-bin/mapserv?map=/data/mapfiles/nemsr.map&service=wfs&version=1.1.0&request=getFeature&typename=nemsr_sites&BBOX=-50,100,0,170

Andre

**Comment by stevage** [comment]
Managed to make this work: http://nationalmap.research.nicta.com.au/neii/ 

(I'm not 100% I got the intent of the catalog structure right, but hopefully it's ok for the demo).

**Comment by kring** [comment]
This is now deployed to staging:
http://staging.neiiviewer.nicta.com.au/

If all looks good to you, I'll point http://neiiviewer.nicta.com.au at this new version tomorrow morning.

**Comment by ChantelleDoan** [comment]
Thanks much for all your effort Kevin, Steve.  We were able to demo this successfully this morning.

Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by kring** [comment]
Glad to hear it went well!  Ready to switch http://neiiviewer.nicta.com.au to point to that new deployment then?

**Comment by ChantelleDoan** [comment]
No, not ready.  This project is still under development at this stage and this is only a test record.  We aim to have an updated list of monitoring site mid June for further testing.  No production release date has been set but will likely be end of June.

Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | cdoan@bom.gov.au<mailto:cdoan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>

**Comment by ChantelleDoan** [comment]
Hi,

I managed to successfully commit an updated neii-nemsr.json to stagining.  We are still testing at this stage and not ready for production release.  I will close this item for now.

Thanks,
Chantelle
