### ISSUE TITLE
featureInfoTemplate and array details

### ISSUE THREAD

**Issue by marissabyrnes** [TerriaJS/neii-viewer#29]
Is it possible to display details of an array in the featureInfoTemplate?

Using the following I am having trouble getting the observingCapabilities to show:

"featureInfoTemplate": "<h1>Site Details</h1><table class='cesium-infoBox-defaultTable'><tbody><tr><th>Description</th><td>{{siteDescription}}</td></tr><tr><th>URL</th><td><a target='_blank' href='{{siteURL}}'>{{siteURL}}</a></td></tr><tr><th>Operating Authority</th><td>{{operatingAuthority.name}}</td></tr><tr><th>Operating Authority URL</th><td>{{operatingAuthority.url}}</td></tr><tr><th>Site Data Licence Type</th><td>{{siteLicence}}</td></tr><tr><th>Site Status</th><td>{{siteStatus}}</td></tr><tr><th>Spatial Reference System</th><td>{{srs_name}}</td></tr><tr><th>Latitude</th><td>{{latitude}}</td></tr><tr><th>Longitude</th><td>{{longitude}}</td></tr><tr><th>Elevation</th><td>{{ahd}}</td></tr><tr><th>{{extensionFieldName1}}</th><td>{{extensionFieldValue1}}</td></tr><tr><th>{{extensionFieldName}}</th><td>{{extensionFieldValue2}}</td></tr><tr><th>{{extensionFieldName3}}</th><td>{{extensionFieldValue3}}</td></tr><tr><th>{{extensionFieldName4}}</th><td>{{extensionFieldValue4}}</td></tr><tr><th>{{extensionFieldName5}}</th><td>{{extensionFieldValue5}}</td></tr></tbody></table><h1>Site Observation Capabilities</h1><table class='cesium-infoBox-defaultTable'><tbody><tr><th>Observed Property</th><td>{{observingCapabilities[0].observedProperty}}</td></tr><tr><th>Procedure</th><td>{{observingCapabilities[0].procedure}}</td></tr><tr><th>Observation Method</th><td>{{observingCapabilities[0].observationMethod}}</td></tr><tr><th>Data Availability</th><td>{{observingCapabilities[0].dataAvailabilityStatus}}</td></tr><tr><th>Sampling Regime</th><td>{{observingCapabilities[0].samplingRegime}}</td></tr><tr><th>First Observation Date</th><td>{{observingCapabilities[0].firstObservationDate}}</td></tr><tr><th>Final Observation Date</th><td>{{observingCapabilities[0].finalObservationDate}}</td></tr></tbody></table>"

I have tried:
- {{observingCapabilities[0].observationMethod}}
- {{observingCapabilities.observationMethod}}
- {{observingCapabilities[0]}}
- {{observingCapabilities[0][0]}}

json: (http://104.236.81.25/cgi-bin/nemsr/get_geojson.py?network_id=4)

          "properties": {
                "name": "Kalumburu", 
                "siteDescriptionL": "Kalumburu", 
                "siteLicence": "open-CC", 
                "siteURL": "http://www.bom.gov.au/clim_data/cdio/metadata/pdf/siteinfo/IDCJMD0040.001019.SiteInfo.pdf", 
                "operatingAuthority": {
                    "name": "Operating Authority URL", 
                    "url": "http://operatingAuthority"
                }, 
                "network_id": "4", 
                "siteStatus": "active", 
                "extensionFieldValue1": "121", 
                "extensionFieldValue2": "No", 
                "extensionFieldValue3": "Lorem ipsum dolor sit amet, mea ea invenire intellegebat, ut has saepe mollis.", 
                "extensionFieldValue4": "Simul habemus duo cu, mei eu quas urbanitas. Id illud exerci mel, cum primis omittam ei. Mel purto vero erat no, putent saperet te vel. Laoreet quaestio te usu, an dicat apeirian mei. No vix erant salutatus quaerendum, ne vel movet fuisset, nullam voluptua efficiantur at pri. Tibique signiferumque eos ad. Eos ne doming constituam, ei suavitate consequat est.", 
                "extensionFieldValue5": "2016-01-18T03:17:46+10:00", 
                "observingCapabilities": [
                    {
                        "observedProperty": "atmosphere-atmosphericTemperature", 
                        "procedure": "http://externalURI.com", 
                        "observationMethod": "aircraftOrAirborne", 
                        "dataAvailabilityStatus": "available-online", 
                        "samplingRegime": "adhoc", 
                        "firstObservationDate": "1941-01-01"
                    }
                ]
            }

**Comment by RacingTadpole** [comment]
Hi! Yes, it should be possible.  The templating is all done with [Mustache](https://github.com/janl/mustache.js#templates), and it can loop through an array like this:

    {{#observingCapabilities}}
        <p>Observation Method: {{observationMethod}}</p>
        <p>Observation Procedure: {{observationProcedure}}</p>
    {{/observingCapabilities}}

etc.
@axman6 has created templates that show data in an array - he may be able to explain it better than me...

**Comment by marissabyrnes** [comment]
Thank you, that worked perfectly
