### ISSUE TITLE
Add Reef Temp data

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#3]
WMS layers with time component. Endpoints are available from the [NEII catalogue](http://neii.gov.au/catalogue).

**Comment by stevage** [comment]
Looks like there are around 10:

eReefs - ReefTemp Next Generation product (Daily Composites - Sea Surface Temperature variables) - Web Map Service

http://ereeftds.bom.gov.au/ereefs/tds/wms/ereefs/RT2_gridAgg_P1D_SST?service=WMS&version=1.3.0&request=GetCapabilities

eReefs - ReefTemp Next Generation product (Daily Composites - Degree Heating Days variables) - Web Map Service

http://ereeftds.bom.gov.au/ereefs/tds/wms/ereefs/RT2_gridAgg_P1D_DHD?service=WMS&version=1.3.0&request=GetCapabilities

eReefs - ReefTemp Next Generation product (Daily Composites - Error variables) - Web Map Service

http://ereeftds.bom.gov.au/ereefs/tds/wms/ereefs/RT2_gridAgg_P1D_ERR?service=WMS&version=1.3.0&request=GetCapabilities

eReefs - ReefTemp Next Generation product (Weekly Composites) - Web Map Service

http://ereeftds.bom.gov.au/ereefs/tds/wms/ereefs/RT2_gridAgg_P1W?service=WMS&version=1.3.0&request=GetCapabilities

eReefs - ReefTemp Next Generation product (Monthly Composites) - Web Map Service

http://ereeftds.bom.gov.au/ereefs/tds/wms/ereefs/RT2_gridAgg_P1M?service=WMS&version=1.3.0&request=GetCapabilities

eReefs - ReefTemp Next Generation product (Seasonal Composites) - Web Map Service

http://ereeftds.bom.gov.au/ereefs/tds/wms/ereefs/RT2_gridAgg_P6M?service=WMS&version=1.3.0&request=GetCapabilities

eReefs - ReefTemp Next Generation product (Annual Composites) - Web Map Service

http://ereeftds.bom.gov.au/ereefs/tds/wms/ereefs/RT2_gridAgg_P1A?service=WMS&version=1.3.0&request=GetCapabilities

eReefs - Reeftemp Next Generation product - OPeNDAP (XML)

http://ereeftds.bom.gov.au/ereefs/tds/catalog/ereef/reeftemp/catalog.xml

**Comment by azzerger** [comment]
Thanks Steve...yes, that sounds fine - probably arranged just like eReefs Marine Water Quality underneath something called eReefs - ReefTemp as the higher level layer name. If the new groups are created this and the other eReefs would go under Oceans.

Andre

**Comment by stevage** [comment]
Ok, I've added them fairly roughly, as raw `wms-getCapabilities` types, which means that every layer is selectable but the end result is a little crude. Perhaps it would be best at this point if you could advise which layers are important, how to title them etc.

Also, I suspect we're missing some display parameters, like a `band` or something. See how the layer is only one color (with holes)? I seem to recall we had this with a layer in Phase I.

<img width="810" alt="screenshot 2016-04-04 17 16 56" src="https://cloud.githubusercontent.com/assets/678344/14240578/54980bec-fa89-11e5-9a86-a7ee47ffdde1.png">

**Comment by azzerger** [comment]
Steve

Let us follow up with the eReefs team – we will need some subject matter expertise to decide on which layers we should display and how to title them. We will be back in touch.

Chantelle – this is something Jamie is best placed to advise on – the simplest approach is perhaps to replicate what is shown for ReefTemp in the Marine Water Quality Dashboard (http://www.bom.gov.au/marinewaterquality/) but Jamie may see logic in displaying all the data. The ReefTemp data services are now visible on the dev site - http://nationalmap.research.nicta.com.au/neii/

Andre

**Comment by azzerger** [comment]
Arthur

This can be closed – the ReefTemp data is now in place in the staging viewer.

Thanks Andre

**Comment by ChantelleDoan** [comment]
Test feedback from Andre:
When one loads a gridded dataset (e.g. reef temp) and it contains a time series the default is that the animation attempts to run (the time series tool at the bottom of the screen). The same happens for Solar. I could be wrong but this appears to use up system resources so it takes longer for gridded data to display. Would it make sense for the default to be that the animation does not run until a user selects it to run and then the grids would render more rapidly?

**Comment by RacingTadpole** [comment]
We do have a global config parameter you can set, `autoPlay`, which can turn the animation-on-load on or off. How about I set it to "off" in the next version and you can see what you think?

**Comment by ChantelleDoan** [comment]
That would be great thanks to test in the next version.

**Comment by ChantelleDoan** [comment]
tested successfully.  Seen improvement in performance.
