### ISSUE TITLE
Customising feature info for WFS results

### ISSUE THREAD

**Issue by marissabyrnes** [TerriaJS/neii-viewer#32]
Hi,

Is there a way to customise the feature info displayed for data that comes from a WFS?  We are currently using the FeatureInfoTemplate for GeoJSON data, but can't seem to get it working for WFS data.

Example WFS output:
[test-wfs.txt](https://github.com/TerriaJS/neii-viewer/files/368410/test-wfs.txt)

Thanks,
Marissa

**Comment by stevage** [comment]
It probably should work - can you give me the WFS endpoint you're using and the catalog file you've got so far, so I can see if I can make it work?

**Comment by marissabyrnes** [comment]
Hi Steve,

Our WFS endpoint is not available externally yet. But we have come across an issue that we are using GML3.2 in our xml and the viewer seems to only support GML3.1.  Are there any plans to support GML3.2?    The other potential problem is that our xml contains complex features and nested elements (see attached 
[ows-updated.txt](https://github.com/TerriaJS/neii-viewer/files/385102/ows-updated.txt)
) and looking at the code it looks like the viewer might convert xml to geoJSON before rendering, is that correct?  So, there may be issues displaying all the data for the features.

So, we are currently looking at continuing to use GeoJSON instead of xml.  

Thanks,
Marissa
