### ISSUE TITLE
Update to new UI

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#35]

**Comment by stevage** [comment]
I've done the skinning and set up a demo here: http://nationalmap.research.nicta.com.au/neii-newui/

@ChantelleDoan, your comments? (Ignore the error message at the start...)

**Comment by azzerger** [comment]
Steve

Thanks for 're-skinning' – Chantelle is off on leave today but let us have a look in coming days and get you some feedback. On first impressions it looks great

One initial question – I realise the UI takes a slightly different approach here but can it support a default view with some data shown? I can see that it’s a case of all or no data but just wondering whether it's possible to have something in the default/start-up view.

Andre

**Comment by stevage** [comment]
By "default view with some data shown", you mean loading some datasets by default? Yes, very easily - we just set add the `isShown: true` attribute to the dataset. 

Chantelle suggested also having the "add data" window pop open by default, which we could probably implement easily if you want it.

(Btw, if possible, could you try to trim all the quoted reply text when you're responding to Github issues from email so it doesn't end up in the issue comment...)

**Comment by azzerger** [comment]
Thanks Steve, yes exactly as you described. We shall have a think regarding whether we take this approach - its a little counter to the new UI. The add data default does make sense - perhaps a good compromise and replacement for the earlier UI approach.
