### ISSUE TITLE
Descriptions for dataset groups

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#36]
The new UI allows dataset _groups_ to have descriptions, an addition to items:

![screenshot 2016-08-22 17 33 30](https://cloud.githubusercontent.com/assets/678344/17846909/913c6d22-688e-11e6-8856-c5d94d8b665b.png)

This would be a good place to have some explanatory text about what a "Conformant" data service is, or what's included in the "Air" category, etc. They can be quite detailed and include markdown text (headings etc), links, copyright statements and so on. 

If you provide me with some copy (or point me to the right place) I'd be happy to implement descriptions. @ChantelleDoan

**Comment by ChantelleDoan** [comment]
Thanks Steve.  This is very helpful.  We will put some text together to send you with the next few weeks after the NEMSR go live.

**Comment by stevage** [comment]
The format for each of these is:

```
          "info": [
            {
              "name": "My subheading",
              "content": "Here's the information that goes under the subheading"
            }
          ]

```

**Comment by ChantelleDoan** [comment]
Duplicate.  Closed.
