### ISSUE TITLE
About NEII Viewer Button

### ISSUE THREAD

**Issue by ChantelleDoan** [TerriaJS/neii-viewer#38]
Hi Steve,

When a user click the "About NEII Viewer" buttion on the map, it takes them to "http://neii.gov.au/viewer/about.html".  Could you make update so that on click, it goes to the now live neii.gov.au page "http://neii.gov.au/data-viewer"

Thanks.
Chantelle

**Comment by stevage** [comment]
I've implemented this in the current (awaiting deployment) version. Not sure how to implement in the new UI.

**Comment by kring** [comment]
@stevage extra buttons are configured in `UserInterface.jsx`.  Take a look at how NM and AREMI do it.

**Comment by ChantelleDoan** [comment]
Closed as this is a duplicate item.
