### ISSUE TITLE
New layers from AREMI

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#39]
Recording a request from Matthew Brooks:
1.       Request addition of the following data services under the relevant NEII Domains, where available using existing configurations of these data services already available in the AREMI renewables skin
### A.      'Land' Domain

1)      Australian World Heritage Areas (already in http://nationalmap.gov.au/renewables/)

2)      Collaborative Australian Protected Areas Database (CAPAD) 2014 (already in http://nationalmap.gov.au/renewables/)

3)      Directory of Important Wetlands in Australia (DIWA) (already in http://nationalmap.gov.au/renewables/)

4)  Australian Topographic Base Map  http://services.ga.gov.au/gis/services/Topographic_Base_Map_WM/MapServer/WMSServer?
### B.      'Water' Domain

AusHydro WMS (already in http://nationalmap.gov.au/renewables/)

**Comment by stevage** [comment]
(Done except for A4, which needs more information)

**Comment by matthew-brooks** [comment]
Unfortunantley both Lisa and myself are not  seeing these updates in the dev NEII Viewer User Interface 2.0, have also tested after cleared my history/cache just in case.
Overall noted it's better to test with Chrome, Not IE11
Also the data catalogue window doesn't open on startup

**Comment by stevage** [comment]
I've now left Data61, but just wanted to follow up - yes, the changes haven't been deployed, as that staging area is no longer suitable to be used this way. Thought I had explained that, sorry. @RacingTadpole will need to deploy to a new server.
