### ISSUE TITLE
Change fonts, colours & other styling 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#44]
Change the size, fonts, colours and other styling items, as per below:  

- [x] Search box:  
  -	Word “Search”: Increase font size to 16px.  
  -	When typing into textbox:  Increase font size to 16px and change font colour to “black” (from green)

- [x] Add data button:
  -	Word “Add data”: Increase font size to 16px. 
  -	Button background colour: Change to Green HEX #BCC94E

- [x] Textbox:
  -	Background colour: Grey (lighter contrast) = HEX #7E7E7E
  -	Font size = 15px

- [x] Left navigation panel:
  -	Background colour: Grey (darker) = HEX #4D4D4D

- [x] Map button/scale:
  -	Background colour: Grey (lighter contrast) = HEX #7E7E7E, hover background colour: Green HEX #BCC94E
  -	Font size = 13px
 
- [x] Add data pop-up - Data catalogue tab
  - [x] Font colours and background colours TBA by the BOM team (@azzerger) 
  - [x] Update all textbox url links font colour and add text decoration underline
 page a:visited { color: #BB5430; text-decoration: underline;}
.page a { color: #632D1A; text-decoration: underline;}

- [x] Feature info panel
  - [x] Download data format: Font colour of the data download format "CSV" and "JSON" hard to read against background. Update font colour = HEX #632D1A, Hover over = HEX #BB5430
![image](https://cloud.githubusercontent.com/assets/18452161/20127048/070580a0-a68f-11e6-8bef-5dbf16a678fc.png)

  - [x] Overall font colours and background colours TBA by the BOM team (@azzerger)

- [x] Feedback panel
  - [x] Change colour to match the other NEII colours;
  - [x] Overall font colour and background colours TBA by the BOM team (@azzerger)

**Comment by ChantelleDoan** [comment]
CD Test Result: 
1.  Search Box: 
The font size of "Search" looks smaller than the font of "Add data" text. Increase font size to be as per "Add data".
2.  Add data pop-up - Data catalogue tab:  
URL links: Some url links fonts are still displayed as green. Eg at "GetCapabilities URL" and "Service Contact"
3.  Feature info panel:  
Still to change font on hover over = HEX #BB5430

**Comment by ChantelleDoan** [comment]
- [ ] Feature Information Popup
1.	Update heading background colour of “Feature Information” and “Site Heading” to #7e7e7e
2.	Update all heading colour to #4D4D4D.
3.	Update all row shading background colour to #EDECEC.
4.	Update table background colour to #FFFFFF. Update table text colour to #4D4D4D.
5.	Widen table width of "site Observation Capabilities" to be the same as the ''Site Details'' table.
![feature info](https://cloud.githubusercontent.com/assets/17890967/20375892/296a60b4-acd6-11e6-95f5-95dcb8442f76.png)

- [ ] Data Catalogue Popup
1.	 Update all heading background colour to #7E7E7E.  On tab that is active, bold the tab heading and update heading text colour to #FFFFFF.
2.	Update text colour to #4D4D4D.  Update background colour to #4D4D4D 
3.	Update background colour to #EDECEC.  Update all heading and layer to #632DIA.  Update active layer to be #BB5430.
![data catalogue](https://cloud.githubusercontent.com/assets/17890967/20375917/5de4f958-acd6-11e6-8809-122c15e0d226.png)

- [ ] Feedback Popup
1.	 Update heading Feedback background colour to #7E7E7E
2.	Update font colour to #4D4D4D.
3.	Update colours of button to be consistent with the "Add Data" button.
![feedback](https://cloud.githubusercontent.com/assets/17890967/20375919/6323ec1c-acd6-11e6-95f0-d6d972eabf5b.png)

**Comment by RacingTadpole** [comment]
@ChantelleDoan - can I just confirm what you want with the Feature Info Panel?
Are you asking for it to have a white background, apart from the very top header line (1 on your diagram)? Ie. the white background would go behind 2 on your diagram too, and any other non-table elements?

**Comment by ChantelleDoan** [comment]
Hi @RacingTadpole, that's correct, white background for everything apart the top header including whitebackground behind #2.

**Comment by RacingTadpole** [comment]
OK, I've tried to implement all of the above. Here are some screenshots - how do these look? :-)

![image](https://cloud.githubusercontent.com/assets/1757858/21037548/ce371ba2-be22-11e6-8454-449e89f4f7ff.png)
![image](https://cloud.githubusercontent.com/assets/1757858/21037559/eac79bfc-be22-11e6-80e8-7776db7f210e.png)
![image](https://cloud.githubusercontent.com/assets/1757858/21037584/17a120e4-be23-11e6-93b6-aeeb77f28072.png)

**Comment by ChantelleDoan** [comment]
Thanks @RacingTadpole.  The updates look great.

Here are my feedback:
1. Feature Information: Update the label text colours to #4D4D4D
![feature info](https://cloud.githubusercontent.com/assets/17890967/21162680/c7fd9fe0-c1e2-11e6-8a4d-2eb82b675c1d.png)

Data Catalogue Pop-up:  
2. Update menu panel background colour to white
![cat](https://cloud.githubusercontent.com/assets/17890967/21162730/0769b394-c1e3-11e6-83d3-b0ed73e76500.png)
3. Update the icon to close page from "Done" icon to "X" icon as per the Feature information and feedback pop-up.

**Comment by RacingTadpole** [comment]
@ChantelleDoan - I suggested a change to TerriaJS https://github.com/TerriaJS/terriajs/pull/2280#issuecomment-268403470 to make it easier to replace the "Done" button with an "✕", but people have raised some valid concerns about the change (specifically it would make internationalisation harder down the track). Also, you'll see at that link that @philipgrimmett from the UX team has pointed out the choice of "Done" was based on user testing:
> The wording was defined in response to usability testing, where users appeared to stall after turning on a dataset (It wasn't clear to them how they should proceed). We wanted to frame 'adding data' as a task to be completed, not the default state. 
Would you be OK with sticking with "Done", at least for now?

**Comment by ChantelleDoan** [comment]
Thanks for your response @philipgrimmett.  My focus was more to ensure consistency as currently the close window button uses a mixture of the "Done" icon and the "X" icon .  Is it possible then to replace all the "X" icon with the "Done" icon?

Seasons greetiongs and have a safe holiday.
