### ISSUE TITLE
Insert introductory text for right-hand pane when clicking on data category

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#46]
BOM to provide text for right-hand pane, for data categories:

![image](https://cloud.githubusercontent.com/assets/18452161/20126045/31513df8-a686-11e6-808d-03abccfa132f.png)

**Comment by RacingTadpole** [comment]
@ChantelleDoan - I looked into this, and it can be done by updating your json file to include a `description` field, eg. ...`{"name": "Geofabric", "type": "group", "description": "Your description goes here", ...}`

**Comment by ChantelleDoan** [comment]
We now have the text.  @RacingTadpole, would you like me to update the json file on github or send it to you to update?

Thanks, Chantelle

**Comment by RacingTadpole** [comment]
Hi Chantelle, I'm more than happy if you can update it directly in github.  Ideally, do it as a separate branch and submit a pull request for the changes - that way I can review it and check it will work.

**Comment by ChantelleDoan** [comment]
Ok.  I'll give it a go.  Thanks.

Regards,
Chantelle Doan | NEII Programme Manager
[Description: Description: cid:389443803@21082013-35A7]
Environmental Information Services
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 9, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4475 | chantelle.doan@bom.gov.au<mailto:chantelle.doan@bom.gov.au> | www.bom.gov.au<http://www.bom.gov.au/>
[app email badge.jpg]<http://www.bom.gov.au/app>

**Comment by ChantelleDoan** [comment]
Hi @RacingTadpole,

All the config files are at the sub-menu directory (eg air, biota etc).  Which file should I  add description text for the main folder directory - "NEII Data Services – Conformant"?  

![data service - conformant](https://cloud.githubusercontent.com/assets/17890967/20656113/46351e46-b57d-11e6-96b4-57f877226f17.gif)

The descriotion text I would like to add is:
Conformance for NEII web data services is determined by the NEII Conformance Framework. The framework uses a maturity model approach outlining the various degrees of conformity.
Specific principles in the framework include the following:
•	Environmental data are made publically available through machine-readable web data services (published online).
•	Structured metadata will support any NEII data release (well described).
•	Providers will make their data available through under an open licence.
•	Data are provided with support structures that provide enduring operational support to users.
•	Data are defined consistently, and definitions are available to users to support re-use (governed and managed).
The first principle is mandatory and in the absence of the availability of environmental data through web data services, NEII conformance is not possible at any level of maturity.
See the [NEII Conformance Framework](http://www.neii.gov.au/system/files/filedepot/1/NEII%20Conformance%20Framework%20Version%201.0%20May%202016.pdf) for a detailed overview of what constitutes conformance.
See [here](http://www.neii.gov.au/web-data-services) for a list of NEII conformant web data services and how to access.


Thanks

**Comment by RacingTadpole** [comment]
Ah, excellent question! You should be able to add it in to any one of the `neii-xyz.ejs` files, at the same level as the name you want to add it to, ie.
```
{
    "catalog": [
        {
            "name": "NEII Data Services – Conformant",
            "type": "group",
            "isOpen": false,
            "description": "YOUR DESCRIPTION GOES HERE",
            "items": [
```

**Comment by ChantelleDoan** [comment]
Hi @RacingTadpole,
I have added all the description text to the config files and ready for you to review the review the pull requests and make the commits.  Thanks.
