### ISSUE TITLE
Search function not returning all expected results

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#47]
Data Catalog search function:  Not returning all related records searched.  
e.g search for "Water".
Result:
a)	 Search is not returning any records under the Environmental Monitoring Sites Register menu.  Expected "Water -> **Water Data Online**" to also be returned.
b)	 The search results returned (see screenshot below) is not displaying the menu headings and sub menu heading which make it hard to understand the results.  Should display as follows:

NEII Data Services – Conformant
---------------------------------------------------
        Oceans: 3
                        Marine water quality (eReefs)
        Water: 3
                        Geofabric
                                        Hydrogeology – Groundwater Cartography
                                                        Water Table Aquifers +
                                                        Water Table Hydraulic Conductivity +
                                                        Water Table Salinity +
                                                        Water Table Yield +
                                                        Water bodies +
                                                        Water Pipeline +
                        Water Observations from Space

Environmental Monitoring Sites Register 
---------------------------------------------------
        Water: 1
                        Water Data Online +
![image](https://cloud.githubusercontent.com/assets/18452161/20126079/70580c7a-a686-11e6-9e23-bb9cc865db46.png)

**Comment by RacingTadpole** [comment]
These two issues are open terriajs issues:
(a) https://github.com/TerriaJS/terriajs/issues/2204
(b) https://github.com/TerriaJS/terriajs/issues/2136.
I'll keep this issue open so we can keep the priority "high" label.

**Comment by RacingTadpole** [comment]
I believe this is fixed in the latest staging version. Please re-open if not.

**Comment by ChantelleDoan** [comment]
Thanks @RacingTadpole.  Tested successfully.
