### ISSUE TITLE
When adding data, filter does not find JSON files automatically

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#48]
When uploading a data file, the file type filter by default did not find JSON files.  The filter on the file browse had to be set to All File Types before it would find a JSON file in any given folder.

This is a bug which has been fixed; @RacingTadpole, please connect to the correct issue number in terriajs.

**Comment by RacingTadpole** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/2198 (when released)
