### ISSUE TITLE
Unclear UX when adding your own data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#49]
When uploading a data file, the user has to go to the ‘About Data window’ to expand the data file out to its component data items.  This was not readily apparent at first when it looked like the file had been uploaded but from the front screen, no data could be viewed.   

- [ ] BOM team to provide screen shots with the issue; at this stage, it's unclear (@azzerger)

**Comment by ChantelleDoan** [comment]
Furthere reviewed and tested and no longer an issue.
