### ISSUE TITLE
Add Context Layers

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#5]
We need to add various ABS boundaries etc from GA/NM:

* CEDs
* LGAs
* NRMAs
* POAs
* SEDs
* SSCs
* STE

**Comment by azzerger** [comment]
Steve, the following contextual layers are a good place to start for us:

Local Gov Areas - http://geoserver.nationalmap.nicta.com.au:80/admin_bnds_abs/wfs?service=WFS&version=1.1.0&request=GetFeature&typeName=admin_bnds:LGA_2011_AUST&srsName=EPSG%3A4326&maxFeatures=1000

States and Territories - http://geoserver.nationalmap.nicta.com.au:80/admin_bnds_abs/wfs?service=WFS&version=1.1.0&request=GetFeature&typeName=admin_bnds:STE_2011_AUST&srsName=EPSG%3A4326&maxFeatures=1000

Postal Areas - http://geoserver.nationalmap.nicta.com.au:80/admin_bnds_abs/wfs?service=WFS&version=1.1.0&request=GetFeature&typeName=admin_bnds:POA_2011_AUST&srsName=EPSG%3A4326&maxFeatures=1000

NRM Regions - http://geoserver.nationalmap.nicta.com.au:80/admin_bnds_abs/wfs?service=WFS&version=1.1.0&request=GetFeature&typeName=admin_bnds:NRMR_2011_AUST&srsName=EPSG%3A4326&maxFeatures=1000

Local Government Areas - http://geoserver.nationalmap.nicta.com.au:80/admin_bnds_abs/wfs?service=WFS&version=1.1.0&request=GetFeature&typeName=admin_bnds:LGA_2011_AUST&srsName=EPSG%3A4326&maxFeatures=1000

**Comment by stevage** [comment]
Please reopen if you'd like more layers added. (Note that you included LGA twice in the above list...)
