### ISSUE TITLE
Sections missing in "About this data set"

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#50]
All the sub menu – information section are missing the information for Data Source Details and Data Service Details. This appeared in the previous skin. See below.
![image](https://cloud.githubusercontent.com/assets/18452161/20126353/83ad5896-a688-11e6-8e90-75f49d65b28d.png)

**Comment by RacingTadpole** [comment]
@kring or @chloeleichen - do either of you know what happened here? In the new UI, we no longer have the "Data Source Details" or "Data Service Details" headings on the catalog item info. 

I don't see any reference to them in the old UI TerriaJS eg. https://github.com/TerriaJS/terriajs/blob/oldui/lib/ViewModels/CatalogItemInfoViewModel.js or in the oldui (master) NEII-viewer, so I'm not quite sure how they got there before...

**Comment by RacingTadpole** [comment]
Actually I have just found it in the old UI at https://github.com/TerriaJS/terriajs/blob/oldui/lib/Views/CatalogItemInfo.html#L128-L134 . 
I should ask instead:  Do you know if we got rid of these sections on purpose?

**Comment by kring** [comment]
We did.  They would have been quite a bit of work to implement the new UI and they were never really very useful.

**Comment by ChantelleDoan** [comment]
Thanks @RacingTadpole.  I will close this item and if need arises in future I will raise a seperate ticket.  Thanks.
