### ISSUE TITLE
Increase the width of the vertical scroll bar

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/neii-viewer#52]
Menu – vertical scroll bar is hard to see. 
![image](https://cloud.githubusercontent.com/assets/18452161/20127014/a9c6d0c4-a68e-11e6-95ac-13642119a053.png)

**Comment by AnaBelgun** [comment]
@RacingTadpole you might need to assign this to front end and UX as well.

**Comment by ChantelleDoan** [comment]
Test successful
