### ISSUE TITLE
My data:  Drag and drop data file adds duplicate layers

### ISSUE THREAD

**Issue by ChantelleDoan** [TerriaJS/neii-viewer#60]
Steps:
- Open a new instance of Viewer.  
- Drag and drop a file, it shows up twice in the right hand navigation pane.  (Interestingly this problem only appears in a new browser instance).  
- If I then click "remove all" button and then drag and drop another file, this problem is not present.  

![duplicate layers](https://cloud.githubusercontent.com/assets/17890967/20127694/6b0b8436-a695-11e6-98aa-a56448517d66.jpg)

**Comment by rowanwins** [comment]
Resolved
