### ISSUE TITLE
Catalog formatting

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/neii-viewer#63]
Catalog changes:
  - [x] start the data catalogue pop-up with collapsed headings (as per the Northern Australia Map). Currently the headings are expanded to the second level
  - [x] Update formatting of the group names to "[groupName] [x number of layers]" see below
![image](https://cloud.githubusercontent.com/assets/18452161/20125953/728a3776-a685-11e6-82af-eb5489f5df21.png)

**Comment by RacingTadpole** [comment]
@azzerger or @ChantelleDoan - you'll need to address the first one of these on get_viewer_config.json, by changing `"isOpen"` to `false` everywhere, eg. like this:
```{
    "catalog": [
        {
            "name": "NEII Data Services – Conformant",
            "type": "group",
            "isOpen": false,
            "items": [ ...]
        }
    ]
}
```

**Comment by ChantelleDoan** [comment]
Thanks.  I will organise for the NEMSR config file to be updated.

**Comment by ChantelleDoan** [comment]
Actioned.
