### ISSUE TITLE
Specify range in timeline control

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#8]
> Re timeline control, explorer enabling the user to specify the timeline range they are interested in, eg beginning and end dates, this is also likely to be beneficial for SOS services.

We think this probably just means being able to zoom in, and hence navigate time series that span many years.

**Comment by stevage** [comment]
This feature doesn't exist in TerriaJS but is in development, I believe.

**Comment by RacingTadpole** [comment]
FYI, you can use your mouse's scroll wheel to zoom in/out of the time slider at the bottom of the map,.
