### ISSUE TITLE
Prod test:  link from related maps on prod is pointing to the NEII Viewer staging site

### ISSUE THREAD

**Issue by ChantelleDoan** [TerriaJS/neii-viewer#85]
On click of the image of the NEII Viewer from the Related Maps list from other maps (ie National Map), it is point to NEII Viewer staging (http://neiiviewer.nicta.com.au/) instead of production (http://neii.gov.au/viewer/). 

![link to viewer staging](https://cloud.githubusercontent.com/assets/17890967/21871042/c18140bc-d8b3-11e6-8182-49fa00770a9b.png)

**Comment by RacingTadpole** [comment]
Found the problem in NationalMap, Northern Australia and AREMI - hopefully they'll all be fixed when they are next released, probably late Feb.

**Comment by ChantelleDoan** [comment]
Tested and issue has been fixed.
