### ISSUE TITLE
Self-service config management

### ISSUE THREAD

**Issue by stevage** [TerriaJS/neii-viewer#9]
We need to develop and document a method whereby NEII people can manage their own catalogs. I suggest that the first stage lets them test a proposed catalog and then we put it into production. The second stage would let them put it straight into production when ready.

**Comment by azzerger** [comment]
Steve, in addition to being able to configure JSON files some user documentation would be helpful. Documentation would describe how to edit/maintain the JSON files – even including some basic mark-ups of an existing JSON file to describe how they are structured (tags, indents etc.)

**Comment by stevage** [comment]
I'm now working on this. It's a bit rough so far but:

http://terria.io/Documentation/CatalogManagement/Initialization-File/

**Comment by azzerger** [comment]
Steve

Thanks – we shall have a closer look – and picking up your rapid demo in today's meeting did you say the file at https://github.com/TerriaJS/neii-viewer/tree/master/wwwroot/init neii.oceans.json<https://github.com/TerriaJS/neii-viewer/tree/master/wwwroot/init%20neii.oceans.json> should be ready to drag and drop onto the viewer to validate how the ReefTemp data is rendering – we can get this ball moving with the data owner if this is the correct file however the drag and drop did not appear to work – I can see it contains the ReefTemp data

Andre

**Comment by stevage** [comment]
I've just updated http://terria.io/Documentation/CatalogManagement/Initialization-File/

You can see the non-prod Reef-Temps data in action here: neii.gov.au/viewer/#neii-oceans

The file is here: https://github.com/TerriaJS/neii-viewer/blob/master/wwwroot/init/neii-oceans.json

You can download it, edit it and either:

- drag-drop into the Viewer to preview it
- host it on the web somewhere it can be accessed, then put that in the URL as described in the doc.

To propose changes, go to the file in Github and click the edit button, eg: https://github.com/TerriaJS/neii-viewer/edit/master/wwwroot/init/neii-biota.json

Paste in your changes, then follow the instructions to create a fork/patch and submit a pull request.

**Comment by azzerger** [comment]
Steve

Thanks –the file seems to work well on production and poorly on the staging site (file attached) – it returns the following error (see screen grab below).

No urgency but just tagging it for future fix.

Andre


[cid:image001.png@01D1A154.25B44130]

**Comment by stevage** [comment]
Your screenshot didn't come through. Looks like replying to Github issues in email only works up to a point :)

**Comment by RacingTadpole** [comment]
Hi @azzerger and/or @ChantelleDoan - can we close this one now?

**Comment by ChantelleDoan** [comment]
Steve created the self-help documentation already.  I will close this item.  Thanks.
